# Generated by Django 3.0.8 on 2020-10-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees',
            field=models.IntegerField(null=True),
        ),
    ]
